#ifndef __PORTABLE__UC1601S__H__
#define __PORTABLE__UC1601S__H__

#include <io.h>

typedef struct UC1601S_GPIO_LOWER {
    const char *GPIO;
    unsigned int CD;
    unsigned int RST;
    unsigned int CS;
    unsigned int RD;
    unsigned int WR;
    unsigned int DB;
} UC1601S_GPIO_LOWER;

#define IO_CLASS_UC1601S_LOWER      IO_CLASS_USER_FIRST
#define UC1601S_LOWER_EXECUTE       IO_CLASS_REQUEST(IO_CLASS_UC1601S_LOWER, 0)

#define UC1601S_LOWER_RESET         IO_CLASS_REQUEST(IO_CLASS_UC1601S_LOWER, 0)
#define UC1601S_LOWER_WRITE_COMMAND IO_CLASS_REQUEST(IO_CLASS_UC1601S_LOWER, 1)
#define UC1601S_LOWER_READ_STATUS   IO_CLASS_REQUEST(IO_CLASS_UC1601S_LOWER, 2)
#define UC1601S_LOWER_READ_DATA     IO_CLASS_REQUEST(IO_CLASS_UC1601S_LOWER, 3)
#define UC1601S_LOWER_WRITE_DATA    IO_CLASS_REQUEST(IO_CLASS_UC1601S_LOWER, 4)

extern const IO_DRIVER UC1601SGPIOLower;

#endif
