TEMPLATE = library
TARGET   = dispatch
SOURCES  = clockmgmt.c dispatch.c userapi.c timer.c util.c devices.c handles.c operations.c \
	stm32l/gpio.c \
	portable/uc1601s_lower_gpio.c

include ../../build/main.mk

